server:
  port : 8081
spring:
  application:
    name: payetonkawa-srvc-server
  out:
    ansi:
      enabled: always
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 100
    url: jdbc:postgresql://localhost:5432/mspr_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    testOnBorrow: true
    testWhileIdel: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdelTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
    platform: postgresql
    poolName: write-datasource
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    com.hogo: DEBUG
    org.springframework.web: DEBUG
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mspr_db?createDataBaseIfNotExist=true
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#      database: mysql
#      database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  frontend:
    link: http://localhost:3000/

#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
